extends Node

enum CLASS_ENUM {SOLDIER, ARCHER, CATAPULT};

var SOLDIER_LIFE = 10;
var SOLDIER_SPEED = 100;

var ARCHER_LIFE = 5;
var ARCHER_RANGE = 100;
var ARCHER_SPEED = 80;

var ARROW_SPEED = 200;
var ARROW_DAMAGE = 1;

var CATAPULT_LIFE = 1;
var CATAPULT_RANGE = 1000;
var CATAPULT_SPEED = 10;

var BALLISTIC_SPEED = 200;
var BALLISTIC_DAMAGE = 10;
