extends Node

enum CLASS_ENUM {SOLDIER, ARCHER, CATAPULT};

var SOLDIER_LIFE = 10;
var SOLDIER_SPEED = 60;

var ARCHER_LIFE = 5;
var ARCHER_RANGE = 200;
var ARCHER_SPEED = 40;
var ARCHER_FIRING_SPEED = 4;

var ARROW_SPEED = 400;
var ARROW_DAMAGE = 1;

var CATAPULT_LIFE = 1;
var CATAPULT_RANGE = 500;
var CATAPULT_SPEED = 20;
var CATAPULT_MINIMUM_RANGE = 100;
var CATAPULT_FIRING_SPEED = 10;

var BALLISTIC_SPEED = 300;
var BALLISTIC_DAMAGE = 5;
