extends Node

enum CLASS_ENUM {SOLDIER, ARCHER, CATAPULT, BRUTE, SCOUT};

var SOLDIER_LIFE = 10;
var SOLDIER_SPEED = 60;

var ARCHER_LIFE = 5;
var ARCHER_RANGE = 200;
var ARCHER_SPEED = 40;
var ARCHER_FIRING_SPEED = 4;
var SOLDIER_DAMAGE = 2;
var SOLDIER_COST = 1;

var ARCHER_COST = 2;

var ARROW_SPEED = 400;
var ARROW_DAMAGE = 1;

var CATAPULT_LIFE = 1;
var CATAPULT_RANGE = 500;
var CATAPULT_SPEED = 20;
var CATAPULT_MINIMUM_RANGE = 100;
var CATAPULT_FIRING_SPEED = 10;

var BALLISTIC_SPEED = 300;
var BALLISTIC_DAMAGE = 5;
var CATAPULT_COST = 5;

var BRUTE_LIFE = 20
var BRUTE_SPEED = 50;
var BRUTE_DAMAGE = 5;
var BRUTE_COST = 3;

var SCOUT_LIFE = 5;
var SCOUT_SPEED = 200;
var SCOUT_DAMAGE = 1;
var SCOUT_COST = 1;
