extends Node2D

@onready var playmat = $Playmat;

const playerUnitTypes: Array[CONSTANTS.CLASS_ENUM] = [CONSTANTS.CLASS_ENUM.SOLDIER, 
	CONSTANTS.CLASS_ENUM.ARCHER, CONSTANTS.CLASS_ENUM.CATAPULT, CONSTANTS.CLASS_ENUM.BRUTE, 
CONSTANTS.CLASS_ENUM.SCOUT];
const enemyPattern: Array[CONSTANTS.CLASS_ENUM] = [CONSTANTS.CLASS_ENUM.SOLDIER,
	CONSTANTS.CLASS_ENUM.ARCHER, CONSTANTS.CLASS_ENUM.CATAPULT];

func _ready() -> void:
	playmat.with(playerUnitTypes, enemyPattern);
